# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-cert-manager
  description: This component creates a Helm release for cert-manager on a Kubernetes cluster
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







